@echo off
echo Isbir Kontrol Paneli Baslatiliyor...
echo Gerekli kutuphaneler kontrol ediliyor...
python -m pip install -r requirements.txt
echo Panel aciliyor, lutfen tarayicinizin acilmasini bekleyin...
streamlit run app.py
pause
